app/programs/views.py
from flask import Flask, render_template, Blueprint, request, redirect, jsonify
from app.database import db
from sqlalchemy import create_engine
from app.models import Program, AgeGroups, ProgramType, program_ages, program_types, neighborhood_programs, Neighborhoods, Regions, neighborhood_zips, ZipCodes
from .forms import programFilterForm, sendTextForm
from twilio.rest import Client
import requests
import os

programs_blueprint = Blueprint('programs', __name__, template_folder='templates')

@programs_blueprint.route('/programs', methods=['GET', 'POST'])
def programs():
	form = programFilterForm(request.form)

	if request.method == "POST":
		return program_search(form)

	else:
		programs = Program.query.join(neighborhood_programs).join(Regions).join(Neighborhoods).all()

		return render_template('programs.html', programs=programs, form=form)

@programs_blueprint.route('/program_search', methods=['GET', 'POST'])
def program_search(search):
	conditions = identify_filters(search)

	all_programs = Program.query.join(program_ages).join(program_types).join(AgeGroups).join(ProgramType).join(neighborhood_programs).join(Regions).join(Neighborhoods).join(neighborhood_zips).join(ZipCodes).filter(*conditions).order_by(Program.name).all()

	form = programFilterForm(request.form)
	return render_template('programs.html', programs=all_programs, form=form)


@programs_blueprint.route('/program_search_home', methods=['GET', 'POST'])
def program_search_home(zip_filter, neighborhood_filter, program_type):
	conditions = identify_filters_home(zip_filter, neighborhood_filter, program_type)

	all_programs = Program.query.join(program_ages).join(program_types).join(AgeGroups).join(ProgramType).join(neighborhood_programs).join(Regions).join(Neighborhoods).join(neighborhood_zips).join(ZipCodes).filter(*conditions).order_by(Program.name).all()

	form = programFilterForm(request.form)

	return render_template('programs.html', programs=all_programs, form=form)

@programs_blueprint.route('/program_view/<program_id>', methods=['GET', 'POST'])
def program_view(program_id):

	programs = Program.query.join(program_ages).join(program_types).join(AgeGroups).join(ProgramType).join(neighborhood_programs).join(Regions).join(Neighborhoods).filter(Program.id == program_id).all()

	info_opening = "Hello! Below you will find the information for " +  programs[0].name + "."
	info_phone = " Organization Phone Number: " + programs[0].organizations.phone
	info_website= " Program Website: " + programs[0].website
	info_address =  " Organization Address: " + programs[0].organizations.address
	program_information = (
		info_opening + 
		info_phone +
		info_website + 
		info_address
	)
	
	form = sendTextForm(request.form, program_information=program_information)

	if form.data['user_number']:
		sendText(form)
	elif form.data['user_email']:
		sendEmail(form)

	return render_template('program_view.html', programs=programs, form=form)


@programs_blueprint.route('/neighborhoods', methods=['GET'])
def neighborhoods():

	all_neighborhoods = Neighborhoods.query.all()

	all_neighborhoods = jsonify([neiborhood.to_dict() for neiborhood in all_neighborhoods])

	return all_neighborhoods

@programs_blueprint.route('/program_regions/<program_name>', methods=['GET'])
def program_regions(program_name):
	form = programFilterForm(request.form)
	data = Program.query.filter(Program.name == program_name).all()
	program_regions = jsonify([neiborhood.to_dict() for neiborhood in data])


	return program_regions

def sendText(form):
	user_number = form.data['user_number']
	program_information = form.data['program_information']

	account_sid = os.environ.get('TWILLIOACCOUNTSID')
	auth_token = os.environ.get('TWILLIOAUTHTOKEN')
	from_phone = os.environ.get('TWILLIONUMBER')

	client = Client(account_sid, auth_token)

	message = client.messages \
	                .create(
	                     body=program_information,
	                     from_=from_phone,
	                     to='+1 ' + user_number
	                 )

def sendEmail(form):
	user_email = form.data['user_email']
	program_information = form.data['program_information']

	domain = os.environ.get('MAILGUNDOMAIN')
	api_key = os.environ.get('MAILGUNAPI')
	request_url = "https://api.mailgun.net/v3/" + domain + "/messages"

	response = requests.post(
	        request_url,
	        auth=("api", api_key),
	        data={"from": "Literaseek <mailgun@" + domain + ">",
	              "to": user_email,
	              "subject": "Hello",
	              "text": program_information})

	print(response.text)
	return response.text

def identify_filters(search):
	search_name = search.data['search_name']
	age_groups_select = search.data['select_age']
	type_select = search.data['select_type']
	open_for_public_school_enrollment = search.data['open_for_public_school_enrollment']
	search_neighborhoods =  search.data["neighborhoods"]
	search_zips =  search.data["zipcodes"]

	conditions = []

	if search_name: 
		conditions.append(Program.name.like('%'+search_name+'%'))

	if age_groups_select:
		conditions.append(AgeGroups.name.in_(age_groups_select))

	if type_select:
		conditions.append(ProgramType.name.in_(type_select))

	if open_for_public_school_enrollment:
		conditions.append(Program.open_public_school_enrollement.is_(open_for_public_school_enrollment))

	if search_neighborhoods:
		conditions.append(Regions.name.in_(search_neighborhoods))

	if search_zips:
		conditions.append(ZipCodes.name.in_(search_zips))

	return conditions

def identify_filters_home(search_zips, search_neighborhoods, type_select):

	conditions = []

	if type_select:
		conditions.append(ProgramType.name.like(type_select))

	if search_neighborhoods:
		conditions.append(Neighborhoods.name.like('%'+search_neighborhoods+'%'))

	if search_zips:
		conditions.append(ZipCodes.name.like('%'+search_zips+'%'))

	return conditions

app/programs/templates/program_view.html
{% extends "base.html" %}

{% block content %}

<div class="container single-view-container">
    <div class="program_view">
		{% for program in programs %}
        <div class="program-view-title">
			<h1 class="program-title"> {{ program.name }} </h1> 
        </div>

        <div class="last-updated-main">
            <p class="search-card-updated-main"> Posting Last Updated: {{ program.last_updated }} </p>
        </div>

        <div class="program-main-content">

            <div class="program-description-main">
              <h2 class="program-main-subheader"> Program Overview </h2>
		      <h3 class="description"> {{ program.description }} </h3>
            </div>

            <div class="contact-info row">
                <div class="col-6">
                    <i class="fas fa-phone teal org-icon" style="margin-bottom:18px"></i>
                    <h3 class="program-phone org-info"> {{ program.organizations.phone }} </h3>
                </div>
                <div class="col-6">
                    <i class="fas fa-tv teal org-icon" style="margin-bottom:18px"></i>
                    <h3 class="program-website org-info"> <a href="{{ program.website }}" style="color:black">{{ program.website }}</a> </h3>
                </div>
            </div>

            {% set Google_URL = "https://maps.google.com/?daddr=" + program.organizations.address + "," + program.organizations.city + "," + program.organizations.state + "," + program.organizations.zipcode%}

            <div class="buttons-row row">
                <div class="col-4">
                    <button id="textBtn" class="program-detail-button"><i class="fas fa-mobile-alt" style="color:white; margin-right:5px; font-size: 25px;"></i> Text Myself Program Information</button>
                </div>
                <div class="col-4">
                    <button id="emailBtn" class="program-detail-button"><i class="fas fa-envelope-open-text" style="color:white; margin-right:5px; font-size: 25px;"></i>Email Myself Program Information</button>
                </div>
                <div class="col-4">
                    <a href="{{Google_URL}}" target="_blank"><button class="program-detail-button"><i class="fas fa-map-signs" style="color:white; margin-right:5px; font-size: 25px;"></i>Get Directions</button> </a>
                </div> 
            </div>

            <!-- /** MODAL **/ -->
            <div id="textModal" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <span class="close1 close">&times;</span>
                <form action="" method="post" novalidate class="program-send-info-form">
                    <p class="modal-title">Your Phone Number:</p>
                    <p class="modal-input">
                        {{ form.user_number }}
                    </p>
                    <p>
                        {{ form.submit2(class_="modal-submit-btn") }}
                    </p>
                </form>
              </div>

            </div>

            <!-- /** EMAIL MODAL **/ -->
            <div id="emailModal" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <span class="close2 close">&times;</span>
                <form action="" method="post" novalidate class="program-send-info-form">
                    <p class="modal-title">Your Email Address:</p>
                    <p class="modal-input">
                        {{ form.user_email }}
                    </p>
                    <p>
                        {{ form.submit2(class_="modal-submit-btn") }}
                    </p>
                </form>
              </div>

            </div>

            <h2 class="program-main-subheader"> Other Program Information </h2>
            <div class="row">
                <div class="col-6">
                    <h2 class="program-main-subheader-3"> Chicago City Region Offered </h2>
                    {% for region in program.regions %}
                        <li class="city-region org-text"> {{region.name }} </li>
                    {% endfor %}
                </div>

                <div class="col-6">
                    <div class="column-stacked">
                        <h2 class="program-main-subheader-3"> Program Type(s)</h2>
                        {% for type in program.program_type %} 
                            {% if type.name == "Create Writing" %}
                                {% set name = "Creative Writing"%}
                                <li class="org-text">{{name}}</li>
                            {% else %}
                            <li class="org-text">{{type.name}}</li>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <div class="column-stacked bottom">
                        <h2 class="program-main-subheader-3"> Program Ages Served</h2>
                        {% for age in program.age_groups %}
                            <li class="org-text">{{age.name}}</li>
                        {% endfor %}
                    </div>
                </div>
            </div>

            {% if program.volunteers_needed == True %}
            <div class="vols-needed-main">
		      <h3 class="vol-content"> This program is looking for volunteers! </h3>
            </div>
            {% elif program.volunteers_needed == False %}
			<div class="vols-needed-main">
              <h3 class="vol-content"> This program is not currently looking for volunteers. </h3>
            </div>
            {% endif %}

            <h2 class="program-main-subheader"> Organization Running this Program </h2>

            {% set full_address = program.organizations.address + ", " + program.organizations.city + ", " + program.organizations.state + ", " + program.organizations.zipcode%}

            <div class="presenting-org-main">
                <h3 class="program-main-subheader-2"> <a href="{{ url_for('organizations.organization_view', organization_id=program.organizations.id) }}" target="_blank" style="color:#4fa79f">{{ program.organizations.name }}</a> </h3>
                <h3 class="org-text"> <i class="fas fa-map-marked-alt" style="font-size:40px; margin-right:6px; color:#4fa79f;"></i> {{ full_address }} </h3>
            </div>

        </div>

  </div>
</div>

{% endfor %}

    <script type="text/javascript" src="{{ url_for('static', filename = 'main.js') }}"></script>

{% endblock %}

app/programs/templates/programs.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-4 map-left">
        <div class="container full-search-container">

        <div class="top-search-bar">
            <h1 class="search-page-title">Programs Search Results</h1>

            <button type="button" class="collapsible filter-open-button">Change Search <i class="fas fa-plus-square plus-icon"></i></button>

            <div class="filter-content">

                <form action="" method="post" novalidate>
                    <dl>
                        <dt> {{ form.search_name.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.search_name(class_="main-search-input")}}<dd>
                    </p>
                    </dl>
                    <dl>
                        <dt> {{ form.select_age.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.select_age(class_="main-search-input-multi")}}<dd>
                    </p>
                    </dl>
                    <dl>
                        <dt> {{ form.select_type.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.select_type(class_="main-search-input-multi")}}<dd>
                    </p>
                    </dl>
                    <dl>
                        <dt> {{ form.neighborhoods.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.neighborhoods(class_="main-search-input-multi")}}<dd>
                    </p>
                    <dl>
                        <dt> {{ form.zipcodes.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.zipcodes(class_="main-search-input-multi")}}<dd>
                    </p>
                    <!-- <dl>
                        <dt> {{ form.open_for_public_school_enrollment.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.open_for_public_school_enrollment(class_="main-search-input-multi")}}<dd>
                    </p>
                    </dl>
-->
                    <div class="align-items-center home-submit">
                        <label class="search-submit-button-all">{{ form.submit1(class_="search-submit-buttom") }} <i class="fas fa-search search-icon"></i></label>
                    </div>
                </form>

            </div>

        </div>

            <div class="seach-results-col">
                {% for program in programs %}
                <div class="program-card">
                	<h1 class="search-card-title"> <a href="{{ url_for('programs.program_view', program_id= program.id) }}" target="_blank" style="color:black">{{ program.name }}</a></h1> 
                	<h3 class="search-card-sub-2"> <a href="{{ program.website }}" target="_blank" style="color:#19afab">{{ program.website }} </a> </h3>
                    <h3 class="search-card-sub-2"> {{ program.descripiton }} </h3>    
                    <h2 class="search-card-sub-1"> Presenting Organization: <a href="{{ url_for('organizations.organization_view', organization_id=program.organizations.id) }}" target="_blank" style="color:black">{{ program.organizations.name }}</a></h2>       
                    <h3 class="search-card-updated"> Last Updated: {{ program.last_updated }}</h3>
                </div>
                {% endfor %} 
            </div>
        </div>
    </div>

    <div class="col-8 map-right">
        <div class="map-container">
            <div id="program_map"></div>
        </div>
    </div>

</div>

    <script type="text/javascript" src="{{ url_for('static', filename = 'program_map.js') }}"></script>

{% endblock %}