app/organizations/views.py
from flask import app, render_template, Blueprint, request, redirect, jsonify
from app.models import Organization, Program, AgeGroups, ProgramType, program_ages, program_types, neighborhood_programs, Neighborhoods, Regions, neighborhood_zips, ZipCodes
from .forms import organizationFilterForm, sendTextForm
from twilio.rest import Client
import click
import requests
import os

organizations_blueprint = Blueprint('organizations', __name__, template_folder='templates')

@organizations_blueprint.route('/organizations', methods=['GET', 'POST'])
def organizations():
	form = organizationFilterForm(request.form)

	if request.method == 'POST':
		return org_search(form)

	else:
		all_organizations = Organization.query.order_by(Organization.name).all()

		return render_template('organizations.html', organizations=all_organizations, form=form)

@organizations_blueprint.route('/organization_view/<organization_id>', methods=['GET', 'POST'])
def organization_view(organization_id):

	organizations = Organization.query.join(Program).join(program_ages).join(program_types).join(AgeGroups).join(ProgramType).join(neighborhood_programs).join(Regions).join(Neighborhoods).join(neighborhood_zips).join(ZipCodes).filter(Organization.id == organization_id).all()

	info_opening = "Hello! Below you will find the information for " +  organizations[0].name + "."
	info_phone = " Organization Phone Number: " + organizations[0].phone
	info_website= " Organization Website: " + organizations[0].website
	info_address =  " Organization Address: " + organizations[0].address
	organization_information = (
		info_opening + 
		info_phone +
		info_website + 
		info_address
	)
	
	form = sendTextForm(request.form, organization_information=organization_information)

	if form.data['user_number']:
		sendText(form)
	elif form.data['user_email']:
		sendEmail(form)

	return render_template('organization_view.html', organizations=organizations, form=form)


@organizations_blueprint.route('/org_search')
def org_search(search):
	conditions = identify_filters(search)

	organizations = Organization.query.join(Program).join(program_ages).join(program_types).join(AgeGroups).join(ProgramType).join(neighborhood_programs).join(Regions).join(Neighborhoods).join(neighborhood_zips).join(ZipCodes).filter(*conditions).all()

	form = organizationFilterForm(request.form)

	return render_template('organizations.html', organizations=organizations, form=form)

@organizations_blueprint.route('/organization_search_home', methods=['GET', 'POST'])
def organization_search_home(zip_filter, neighborhood_filter, program_type):
	conditions = identify_filters_home(zip_filter, neighborhood_filter, program_type)

	organizations = Organization.query.join(Program).join(program_ages).join(program_types).join(AgeGroups).join(ProgramType).join(neighborhood_programs).join(Regions).join(Neighborhoods).join(neighborhood_zips).join(ZipCodes).filter(*conditions).all()

	form = organizationFilterForm(request.form)

	return render_template('organizations.html', organizations=organizations, form=form)

@organizations_blueprint.route('/organization_data', methods=['GET', 'POST'])
def organization_data():
	org_ids = request.args.getlist('ids[]')
	
	organizations = Organization.query.filter(Organization.id.in_(org_ids)).all()

	organizations = jsonify([organization.to_dict() for organization in organizations])

	return organizations

def identify_filters(search):
	search_name = search.data['search_name']
	age_groups_select = search.data['select_age']
	type_select = search.data['select_type']
	search_neighborhoods =  search.data["neighborhoods"]
	search_zips =  search.data["zipcodes"]

	conditions = []

	if search_name: 
		conditions.append(Organization.name.like('%'+search_name+'%'))

	if age_groups_select:
		conditions.append(AgeGroups.name.in_(age_groups_select))

	if type_select:
		conditions.append(ProgramType.name.in_(type_select))

	if search_neighborhoods:
		conditions.append(Regions.name.in_(search_neighborhoods))

	if search_zips:
		conditions.append(ZipCodes.name.in_(search_zips))

	return conditions

def identify_filters_home(search_zips, search_neighborhoods, type_select):

	conditions = []

	if type_select:
		conditions.append(ProgramType.name.like(type_select))

	if search_neighborhoods:
		conditions.append(Neighborhoods.name.like('%'+search_neighborhoods+'%'))

	if search_zips:
		conditions.append(ZipCodes.name.like('%'+search_zips+'%'))

	return conditions

def sendText(form):
	user_number = form.data['user_number']
	program_information = form.data['program_information']

	account_sid = os.environ.get('TWILLIOACCOUNTSID')
	auth_token = os.environ.get('TWILLIOAUTHTOKEN')
	from_phone = os.environ.get('TWILLIONUMBER')

	client = Client(account_sid, auth_token)

	message = client.messages \
	                .create(
	                     body=program_information,
	                     from_=from_phone,
	                     to='+1 ' + user_number
	                 )

def sendEmail(form):
	user_email = form.data['user_email']
	program_information = form.data['program_information']

	domain = os.environ.get('MAILGUNDOMAIN')
	api_key = os.environ.get('MAILGUNAPI')
	request_url = "https://api.mailgun.net/v3/" + domain + "/messages"

	response = requests.post(
	        request_url,
	        auth=("api", api_key),
	        data={"from": "Literaseek <mailgun@" + domain + ">",
	              "to": user_email,
	              "subject": "Hello",
	              "text": program_information})

	print(response.text)
	return response.text

app/organizations/templates/organization_view.html
{% extends "base.html" %}

{% block content %} 

<div class="container single-view-container">
    <div class="program_view">
		{% for organization in organizations %}
        <div class="program-view-title">
			<h1 class="program-title"> {{ organization.name }} </h1> 
        </div>

        <div class="last-updated-main">
            <p class="search-card-updated-main"> Posting Last Updated: {{ organization.last_updated }} </p>
        </div>

        <div class="program-main-content">

            <div class="program-description-main">
              <h2 class="program-main-subheader"> Organization Overview </h2>
		      <h3 class="description"> {{ organization.description }} </h3> 
            </div>

            <div class="contact-info row">
                <div class="col-4">
                    <i class="fas fa-phone teal org-icon" style="margin-bottom:18px"></i> 
                    <h3 class="organization-website org-info"> {{ organization.phone }} </h3>
                </div>
                <div class="col-4">
                    <i class="fas fa-tv teal org-icon" style="margin-bottom:18px"></i>
                    <h3 class="organization-website org-info"> <a href="{{ organizations.website }}" style="color:black">{{ organization.website }}</a> </h3>
                </div>

                {% set full_address = organization.address + ", " + organization.city + ", " + organization.state + ", " + organization.zipcode %}

                <div class="col-4">
                    <i class="fas fa-map-marker-alt teal org-icon" style="margin-bottom:18px"></i> 
                    <h3 class="organization-website org-info"> {{ full_address }} </h3>
                </div>
            </div>

            {% set Google_URL = "https://maps.google.com/?daddr=" + organization.address + "," + organization.city + "," + organization.state + "," + organization.zipcode%}

            <div class="buttons-row row">
                <div class="col-4">
                    <button id="textBtn" class="program-detail-button"><i class="fas fa-mobile-alt" style="color:white; margin-right:5px; font-size: 25px;"></i>Text Myself this Information</button>
                </div>
                <div class="col-4">
                    <button id="emailBtn" class="program-detail-button"><i class="fas fa-envelope-open-text" style="color:white; margin-right:5px; font-size: 25px;"></i>Email Myself this Information</button>
                </div>
                <div class="col-4">
                    <a href="{{Google_URL}}" target="_blank"><button class="program-detail-button"><i class="fas fa-map-signs" style="color:white; margin-right:5px; font-size: 25px;"></i>Get Directions</button> </a>
                </div> 
            </div>

            <!-- /** MODAL **/ -->
            <div id="textModal" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <span class="close1 close">&times;</span>
                <form action="" method="post" novalidate class="program-send-info-form">
                    <p class="modal-title">Your Phone Number:</p>
                    <p class="modal-input">
                        {{ form.user_number }}
                    </p>
                    <p>
                        {{ form.submit2(class_="modal-submit-btn") }}
                    </p>
                </form>
              </div>

            </div>

            <!-- /** EMAIL MODAL **/ -->
            <div id="emailModal" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <span class="close2 close">&times;</span>
                <form action="" method="post" novalidate class="program-send-info-form">
                    <p class="modal-title">Your Email Address:</p>
                    <p class="modal-input">
                        {{ form.user_email }}
                    </p>
                    <p>
                        {{ form.submit2(class_="modal-submit-btn") }}
                    </p>
                </form>
              </div>

            </div>

            <h2 class="program-main-subheader"> Programs Ran by {{ organization.name }} </h2>

            <div class="presenting-org-main">
                {% for program in organization.programs %}
                <h3 class="program-main-subheader-2" style="margin-top: 10px"> <a href="{{ url_for('programs.program_view', program_id= program.id) }}" target="_blank" style="color:black">{{ program.name }}</a> </h3>

                <div class="row org-program-row">
                    <div class="col-6">
                        <h2 class="program-main-subheader-3"> Program Ages Served</h2>
                        {% for age in program.age_groups %}
                            <li class="org-text">{{age.name}}</li>
                        {% endfor %}
                    </div>

                    <div class="col-6">
                        <h2 class="program-main-subheader-3"> Program Type(s)</h2>
                        {% for type in program.program_type %}
                            {% if type.name == "Create Writing" %}
                                {% set name = "Creative Writing"%}
                                <li class="org-text">{{name}}</li>
                            {% else %}
                                <li class="org-text">{{type.name}}</li>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>

                {% endfor %}
            </div>


        </div>

  </div>
</div>


{% endfor %}

    <script type="text/javascript" src="{{ url_for('static', filename = 'main.js') }}"></script>

{% endblock %}

app/organizations/templates/organizations.html
{% extends "base.html" %} 

{% block content %}


<div class="row">
    <div class="col-4 map-left">
        <div class="container full-search-container">

        <div class="top-search-bar">
            <h1 class="search-page-title">Organizations Search Results</h1>

            <button type="button" class="collapsible filter-open-button">Change Search <i class="fas fa-plus-square plus-icon"></i></button>

            <div class="filter-content">

                <form action="" method="post" novalidate>
                    <dl>
                        <dt> {{ form.search_name.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.search_name(class_="main-search-input")}}<dd>
                    </p>
                    </dl>
                    <dl>
                        <dt> {{ form.select_age.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.select_age(class_="main-search-input-multi")}}<dd>
                    </p>
                    </dl>
                    <dl>
                        <dt> {{ form.select_type.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.select_type(class_="main-search-input-multi")}}<dd>
                    </p>
                    </dl>
                    <dl>
                        <dt> {{ form.neighborhoods.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.neighborhoods(class_="main-search-input-multi")}}<dd>
                    </p>
                    <dl>
                        <dt> {{ form.zipcodes.label(class_="main-search-label")}} </dt> 
                        <dd>{{ form.zipcodes(class_="main-search-input-multi")}}<dd>
                    </p>
                    <div class="align-items-center home-submit">
                        <label class="search-submit-button-all">{{ form.submit1(class_="search-submit-buttom") }} <i class="fas fa-search search-icon"></i></label>
                    </div>
                </form>

            </div>

        </div>


            <div class="seach-results-col">
                {% for organization in organizations %}
                <div class="program-card">
                    <p class="hide"> {{ organization.id }}</p>
                    <h1 class="search-card-title"> <a href="{{ url_for('organizations.organization_view', organization_id= organization.id) }}" target="_blank" style="color:black">{{ organization.name }}</a></h1> 
                    <h3 class="search-card-sub-2"> <a href="{{ organization.website }}" target="_blank" style="color:#19afab">{{ organization.website }} </a> </h3>
                    <h3 class="search-card-sub-2"> {{ organization.phone }}</h3>
<!--                         <h3 class="search-card-sub-2"> {{ organization.description }} </h3>  -->         
                    <h3 class="search-card-updated"> Last Updated: {{ organization.last_updated }}</h3>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="col-8 map-right">
        <div class="map-container">
            <div id="organization_map"></div>
        </div>
    </div>

</div>

<div id="all_orgs" class="all_orgs hide" style="visibility: hidden">
    {% for organization in organizations %}
        {{ organization.id }},
    {% endfor %}
</div>



<script type="text/javascript" src="{{ url_for('static', filename = 'organization_map.js') }}"></script>

{% endblock %}